# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Score logm
#'
#' @param eta Linear predictor (n x (d + dx(d+1)/2) matrix).
#' @param y Outcome (n x d matrix).
#' @param res Memory initialization
#' @export
NULL

d1_logm <- function(eta, y, res) {
    .Call(`_SCM_d1_logm`, eta, y, res)
}

#' Score mcd
#'
#' @param eta Linear predictor (n x (d + dx(d+1)/2) matrix).
#' @param y Outcome (n x d matrix).
#' @param res Memory initialization
#' @export
NULL

d1_mcd <- function(eta, y, res) {
    .Call(`_SCM_d1_mcd`, eta, y, res)
}

#' Hessian logm
#'
#' @param eta Linear predictor (n x (d + dx(d+1)/2) matrix).
#' @param y Outcome (n x d matrix).
#' @param res Memory initialization
#' @export
NULL

d2_logm <- function(eta, y, res) {
    .Call(`_SCM_d2_logm`, eta, y, res)
}

#' Hessian mcd
#'
#' @param eta Linear predictor (n x (d + dx(d+1)/2) matrix).
#' @param y Outcome (n x d matrix).
#' @param res Memory initialization
#' @export
NULL

d2_mcd <- function(eta, y, res) {
    .Call(`_SCM_d2_mcd`, eta, y, res)
}

jacobian_mcd <- function(eta, res, d, S_row, S_col, rc_idx_s, rc_idx_t) {
    .Call(`_SCM_jacobian_mcd`, eta, res, d, S_row, S_col, rc_idx_s, rc_idx_t)
}

#' Log-likelihood matrix logM
#'
#' @param eta Linear predictor (n x (d + dx(d+1)/2) matrix).
#' @param y Outcome (n x d matrix).
#' @export
NULL

ll_logm <- function(eta, y) {
    .Call(`_SCM_ll_logm`, eta, y)
}

#' Log-likelihood matrix mcd
#'
#' @param eta Linear predictor (n x (d + dx(d+1)/2) matrix).
#' @param y Outcome (n x d matrix).
#' @export
NULL

ll_mcd <- function(eta, y) {
    .Call(`_SCM_ll_mcd`, eta, y)
}

logM_Sigma <- function(x, d) {
    .Call(`_SCM_logM_Sigma`, x, d)
}

logm_decomposition <- function(X) {
    .Call(`_SCM_logm_decomposition`, X)
}

lt_inversion <- function(X) {
    .Call(`_SCM_lt_inversion`, X)
}

mcd_LD <- function(x, d) {
    .Call(`_SCM_mcd_LD`, x, d)
}

mcd_Sigma <- function(L, D, d) {
    .Call(`_SCM_mcd_Sigma`, L, D, d)
}

mcd_decomposition <- function(X) {
    .Call(`_SCM_mcd_decomposition`, X)
}

precision <- function(X) {
    .Call(`_SCM_precision`, X)
}

pred_logm <- function(eta, res, d) {
    .Call(`_SCM_pred_logm`, eta, res, d)
}

pred_mcd <- function(eta, res, d) {
    .Call(`_SCM_pred_mcd`, eta, res, d)
}

