# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Score logm
#'
#' @param eta Linear predictor (n x (d + dx(d+1)/2) matrix).
#' @param y Outcome (n x d matrix).
#' @param res Memory initialization
#' @export
NULL

#' Score mcd
#'
#' @param eta Linear predictor (n x (d + dx(d+1)/2) matrix).
#' @param y Outcome (n x d matrix).
#' @param res Memory initialization
#' @export
NULL

d1_mcd <- function(eta, y, res) {
    .Call(`_SCM_d1_mcd`, eta, y, res)
}

#' Hessian logm
#'
#' @param eta Linear predictor (n x (d + dx(d+1)/2) matrix).
#' @param y Outcome (n x d matrix).
#' @param res Memory initialization
NULL

#' Hessian mcd
#'
#' @param eta Linear predictor (n x (d + dx(d+1)/2) matrix).
#' @param y Outcome (n x d matrix).
#' @param res Memory initialization
#' @export
NULL

d2_mcd <- function(eta, y, res) {
    .Call(`_SCM_d2_mcd`, eta, y, res)
}

#' Log-likelihood matrix logM
#'
#' @param eta Linear predictor (n x (d + dx(d+1)/2) matrix).
#' @param y Outcome (n x d matrix).
#' @export
NULL

#' Log-likelihood matrix mcd
#'
#' @param eta Linear predictor (n x (d + dx(d+1)/2) matrix).
#' @param y Outcome (n x d matrix).
#' @export
NULL

ll_mcd <- function(eta, y) {
    .Call(`_SCM_ll_mcd`, eta, y)
}

lt_inversion <- function(X) {
    .Call(`_SCM_lt_inversion`, X)
}

mcd_LD <- function(x, d) {
    .Call(`_SCM_mcd_LD`, x, d)
}

mcd_Sigma <- function(L, D, d) {
    .Call(`_SCM_mcd_Sigma`, L, D, d)
}

pred_mcd <- function(eta, res, d) {
    .Call(`_SCM_pred_mcd`, eta, res, d)
}

