# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

score_mcd <- function(eta, y, res) {
    .Call(`_SCM_d1_mcd`, eta, y, res)
}

#' Score
#'
#' @param eta Linear predictor (n x (d + dx(d+1)/2) matrix).
#' @param y Outcome (n x d matrix).
#' @param res Memory initialization
#' @export
score_logm <- function(eta, y, res) {
    .Call(`_SCM_d1_logm`, eta, y, res)
}

hessian_mcd <- function(eta, y, res) {
    .Call(`_SCM_d2_mcd`, eta, y, res)
}

#' Hessian
#'
#' @param eta Linear predictor (n x (d + dx(d+1)/2) matrix).
#' @param y Outcome (n x d matrix).
#' @param res Memory initialization
#' @export
hessian_logm <- function(eta, y, res) {
    .Call(`_SCM_d2_logm`, eta, y, res)
}

ll_mcd <- function(eta, y) {
    .Call(`_SCM_logL_mcd`, eta, y)
}

#' Log-likelihood matrix logarithm reparameterization
#'
#' @param eta Linear predictor (n x (d + dx(d+1)/2) matrix).
#' @param y Outcome (n x d matrix).
#' @export
ll_logm <- function(eta, y) {
    .Call(`_SCM_logL_logm`, eta, y)
}

